name: Sync accounts to YNAB(You Need A Budget) every day at 6AM
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 6 * * *  # Every day at 6AM
  push:
      branches:
        - trunk
jobs:
  sync:
    env: # Mimics the .env file in the root of the repository
      YNAB_TOKEN: ${{ secrets.YNAB_TOKEN }}
      PLUGGY_CLIENT_ID: ${{ secrets.PLUGGY_CLIENT_ID }}
      PLUGGY_CLIENT_SECRET: ${{ secrets.PLUGGY_CLIENT_SECRET }}

      ACCOUNT_0_NAME: ${{ vars.ACCOUNT_0_NAME }}
      ACCOUNT_0_PLUGGY_ID: ${{ secrets.ACCOUNT_0_PLUGGY_ID }}
      ACCOUNT_0_YNAB_BUDGET_ID: ${{ secrets.ACCOUNT_0_YNAB_BUDGET_ID }}
      ACCOUNT_0_YNAB_ID: ${{ secrets.ACCOUNT_0_YNAB_ID }}

      ACCOUNT_1_NAME: ${{ vars.ACCOUNT_1_NAME }}
      ACCOUNT_1_PLUGGY_ID: ${{ secrets.ACCOUNT_1_PLUGGY_ID }}
      ACCOUNT_1_YNAB_BUDGET_ID: ${{ secrets.ACCOUNT_1_YNAB_BUDGET_ID }}
      ACCOUNT_1_YNAB_ID: ${{ secrets.ACCOUNT_1_YNAB_ID }}

      ACCOUNT_2_NAME: ${{ vars.ACCOUNT_2_NAME }}
      ACCOUNT_2_PLUGGY_ID: ${{ secrets.ACCOUNT_2_PLUGGY_ID }}
      ACCOUNT_2_YNAB_BUDGET_ID: ${{ secrets.ACCOUNT_2_YNAB_BUDGET_ID }}
      ACCOUNT_2_YNAB_ID: ${{ secrets.ACCOUNT_2_YNAB_ID }}

      ACCOUNT_3_NAME: ${{ vars.ACCOUNT_3_NAME }}
      ACCOUNT_3_PLUGGY_ID: ${{ secrets.ACCOUNT_3_PLUGGY_ID }}
      ACCOUNT_3_YNAB_BUDGET_ID: ${{ secrets.ACCOUNT_3_YNAB_BUDGET_ID }}
      ACCOUNT_3_YNAB_ID: ${{ secrets.ACCOUNT_3_YNAB_ID }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
      - run: uv --version
      - name: Install Python
        run: uv python install  # Installs the version in the .python-version file in the root of the repo
      - run: uv run python --version
      - name: Run sync to YNAB
        run: make run
